/**
 * Full-screen service report card.
 *
 * Displays the structured service report generated by Gemini's
 * generate_report function call. Supports sharing via Web Share API.
 *
 * Depends on: @/types (ServiceReport), @/components/ui/card, @/components/ui/button
 * Used by: session-screen.tsx
 */

import { FileText, Share2, X } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import type { ServiceReport } from "@/types";

interface ReportCardProps {
  report: ServiceReport;
  onClose: () => void;
}

function formatTimestamp(ms: number): string {
  return new Date(ms).toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function buildShareText(report: ServiceReport): string {
  let text = `Service Report — ${report.equipment}\n\n`;
  text += `Diagnosis: ${report.diagnosis}\n`;
  text += `Actions Taken: ${report.actionsTaken}\n`;
  if (report.partsUsed) text += `Parts Used: ${report.partsUsed}\n`;
  if (report.followUp) text += `Follow-Up: ${report.followUp}\n`;
  text += `\nGenerated: ${formatTimestamp(report.generatedAt)}`;
  text += `\n\n— LARIA Field Agent`;
  return text;
}

export function ReportCard({ report, onClose }: ReportCardProps) {
  const handleShare = async () => {
    const text = buildShareText(report);

    if (navigator.share) {
      try {
        await navigator.share({
          title: `Service Report — ${report.equipment}`,
          text,
        });
      } catch {
        // User cancelled share
      }
    } else {
      await navigator.clipboard.writeText(text);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
      <Card className="w-full max-w-md max-h-[90vh] overflow-y-auto bg-zinc-900 border-zinc-700">
        <CardHeader className="relative">
          <div className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-green-400" />
            <CardTitle className="text-lg text-white">
              Service Report
            </CardTitle>
          </div>
          <Button
            variant="ghost"
            size="icon"
            className="absolute top-4 right-4 h-8 w-8 text-zinc-400 hover:text-white"
            onClick={onClose}
          >
            <X className="h-4 w-4" />
          </Button>
        </CardHeader>

        <CardContent className="space-y-4">
          <ReportSection label="Equipment" value={report.equipment} />
          <ReportSection label="Diagnosis" value={report.diagnosis} />
          <ReportSection label="Actions Taken" value={report.actionsTaken} />
          {report.partsUsed && (
            <ReportSection label="Parts Used" value={report.partsUsed} />
          )}
          {report.followUp && (
            <ReportSection label="Follow-Up" value={report.followUp} />
          )}
          <div className="pt-2 border-t border-zinc-800">
            <p className="text-xs text-zinc-500">
              Generated {formatTimestamp(report.generatedAt)}
            </p>
          </div>
        </CardContent>

        <CardFooter className="gap-2">
          <Button
            variant="outline"
            className="flex-1 border-zinc-700 text-zinc-300 hover:text-white"
            onClick={handleShare}
          >
            <Share2 className="h-4 w-4 mr-2" />
            Share
          </Button>
          <Button
            className="flex-1 bg-green-600 hover:bg-green-700 text-white"
            onClick={onClose}
          >
            Done
          </Button>
        </CardFooter>
      </Card>
    </div>
  );
}

function ReportSection({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div>
      <p className="text-xs text-zinc-400 uppercase tracking-wider mb-1">
        {label}
      </p>
      <p className="text-sm text-zinc-200">{value}</p>
    </div>
  );
}
